language: python
python:
  - "3.5"
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install git+https://github.com/kyouko-taiga/stew
# command to run tests
script: 
  - py.test --cov-report=
after_success:
  - coveralls

